### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/appstoreconnect-swift-sdk#1]
Besides Cocoapods support, it would be great to have support for Carthage

**Comment by phimage** [comment]
To support Carthage 
- Have tagged version on github (or the user Cartfile will need a revision or HEAD)
- Create an Xcode projet with shared scheme
- Create a Cartfile with dependencies (Alamofire)

---

We could create the projet with `swift package generate-xcodeproj`

The project generated by `swift package generate-xcodeproj` has minimum macOS version 10.10 or it will compile only with macOS 10.12

One way to change it automatically is to create a `Package.xcconfig` which contains
```
MACOSX_DEPLOYMENT_TARGET=10.12
```
and launch 
```
swift package generate-xcodeproj --xcconfig-overrides Package.xcconfig
```

Then the project must be commited and updated

---

If we do not want to commit the xcode project, user could do:

In the Cartfile
```ruby
github "AvdLee/appstoreconnect-swift-sdk" "HEAD"
```
then get the source 
```
carthage checkout
```
create the Xcode project (with macOS 12, so with Package.xcconfig)
```
(cd Carthage/Checkouts/appstoreconnect-swift-sdk/ && swift package generate-xcodeproj --xcconfig-overrides Package.xcconfig)
```
and build
```
carthage build
```

**Comment by AvdLee** [comment]
I'm not that experienced with Carthage, but creating an Xcode project feels like a lot of overhead for only this support. The Cartfile sounds good to me with the least amount of impact. Do you agree @phimage ?

**Comment by phimage** [comment]
Cartfile is like podspec but not sufficient.
It help only to download and compile a third party framework in the Carthage folder.

An Xcode projet is mandatory (until carthage want to auto create the projet maybe with SPM https://github.com/Carthage/Carthage/pull/1945 )

---

Yes this is an overhead that's why I make this "how to"  for user

But a lot of people want to do 
`carthage update` (one step for `carthage checkout` `carthage build`), so this is just a "crappy" workaround

Then I think that carthage prefer to have one target by OS, not like SPM generate it 
but I try my "how to" and it compile for all OS

**Comment by AvdLee** [comment]
Hmm, we could also go for an Xcode project and use that as the main testing project on CI as well. We now use the CocoaPods example project, but that doesn't always work nicely together with code coverage reporting.

If you like, you can create a PR with Carthage support. Happy to review it quickly!

**Comment by ethanhuang13** [comment]
CupertinoJWT just added [Carthage support](https://github.com/ethanhuang13/CupertinoJWT/pull/8) recently. From my experience, it's recommended to add version tags then Carthage can be supported easily. 

However, to support user use more than one platform in a project with Carthage (say, iOS + watchOS both use appstoreconnect-swift-sdk), this SDK needs to add target per platform.

**Comment by JetForMe** [comment]
Carthage support makes it very easy to incorporate a library, so I highly recommend it, and creating an Xcode project is entirely appropriate for this.

**Comment by JetForMe** [comment]
Any progress on this?

**Comment by AvdLee** [comment]
@JetForMe as far as I know this is still open to be implemented. Feel free to open a PR to add support!

**Comment by JetForMe** [comment]
If I knew how, I'd be happy to!

**Comment by AvdLee** [comment]
@JetForMe It's all described here: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

It shouldn't take a whole lot of effort. In fact, I'm somehow surprised it's not already supported. Did you run into specific errors when trying to use the framework through Carthage?
