### ISSUE TITLE
Replace hand crafted code with code generated from OpenAPI Spec

### ISSUE THREAD

**Issue by orj** [AvdLee/appstoreconnect-swift-sdk#110]
The AppStoreConnect API team have published a OpenAPI 3 spec (https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip). It seems to me that instead of handcrafting a client SDK we should be using [Swagger code-gen](https://github.com/swagger-api/swagger-codegen) to produce a client based on this specification.

Thoughts?

My suggestion that this would be a major v2 release of this project as it would likely be a massively breaking change.

**Comment by AvdLee** [comment]
Although I'm not experienced with OpenAPI specs, it does sound like a good step forward. I do agree with @MortenGregersen , I've always intended to keep out external dependencies to keep this framework lightweight. 

I'm currently not able to jump on this but feel free to get this started!

**Comment by AvdLee** [comment]
This is now done!
