### ISSUE TITLE
App Store Review Submissions

### ISSUE THREAD

**Issue by ignatovv** [AvdLee/appstoreconnect-swift-sdk#112]
Guys, are there any clues on the new section of App Store Connect API - App Store Review Submissions? I think it is an essential functionality for this SDK. Is anyone working on this or I should consider contributing new endpoints?

**Comment by AvdLee** [comment]
> Is anyone working on this or I should consider contributing new endpoints?

I'm not aware of anyone working on this. Feel free to add your contribution!

**Comment by AvdLee** [comment]
This is now available!

![CleanShot 2022-07-17 at 14 45 50@2x](https://user-images.githubusercontent.com/4329185/179398999-07da2f22-2c32-4d9d-bc8f-147ce1b99a95.jpg)
