### ISSUE TITLE
Build fail when run cocoapods example project

### ISSUE THREAD

**Issue by ChenDongnan** [AvdLee/appstoreconnect-swift-sdk#115]
1. When I run the example project, it shows an error 'PhaseScriptExecution failed with a nonzero exit code'.  After I delete the script in Build Phase-Swift lint and the error is gone.

2. I want to know whether the 'Xcode 10 Build System Caching Fix' Item in Build Phases is to fix the bug that after changing some code in development pods and run project under new build system but it doesn't work, unless clean the project first and build.

**Comment by AvdLee** [comment]
This should be solved by following: https://github.com/AvdLee/appstoreconnect-swift-sdk#development
