### ISSUE TITLE
Question: How to download Profiles?

### ISSUE THREAD

**Issue by victorBaro** [AvdLee/appstoreconnect-swift-sdk#118]
Hello, I am enjoying using this SDK through a cli.

I am using the listProfiles endpoint `provider.request(.listProfiles())`, and I am getting back the list of profiles correctly. 

However, I don't know how should I save each profile as `.mobileProvision` files on disk. I thought I could write `profile.attributes.profileContent` (of type string) to a file, but unfortunately doesn't work.

Could you provide with any guidance if you have faced this problem?

Thank you in advance!

**Comment by MortenGregersen** [comment]
It has been some time since I took a quick look at the property. Isn't the content base64 encoded?

**Comment by victorBaro** [comment]
Thank you @MortenGregersen !
I was decoding it wrong. It worked when I used base64.
