### ISSUE TITLE
Modify Provisioning Profiles

### ISSUE THREAD

**Issue by Sanzenbacher** [AvdLee/appstoreconnect-swift-sdk#120]
Hi,

we have many profiles in our apple dev portal and it is always annoying when a new device has been bought. Because then we have to add the device for every profile in order for our QA to be able to install it.

My idea is to automated this step. I looked into your framework and used it to download the provisioning profiles. But I saw no way to change them.

I am not sure that this is even possible.

If it is possible I would like to implement it for you. I never worked on a public git repo, so I am not sure what the process will be. Can I just push a new branch in this repo and you will review it?

Greetings,

Sascha Sanzenbacher

**Comment by Sanzenbacher** [comment]
When I implement an ModifyProfile method which patches a specific profile, I get the http response 403. I guess apple doesn't allow it.

Can someone confirm this?

**Comment by MortenGregersen** [comment]
As per documentation it is only possible to create and delete profiles:
https://developer.apple.com/documentation/appstoreconnectapi/profiles
