### ISSUE TITLE
APIProvider fails to authorize requests 25 minutes after sending the first request

### ISSUE THREAD

**Issue by abdulowork** [AvdLee/appstoreconnect-swift-sdk#137]
## How to reproduce:
1. Create an `APIProvider` and call any request. 
2. Sleep for 25 minutes and call another request.

## Why it happens:
`APIProvider` holds a reference to `JWTRequestsAuthenticator` instance that manages requests authorization.

https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/58ab9330e94c0183ae51aaae972a7be9ca95555e/Sources/APIProvider.swift#L104

When `JWTRequestsAuthenticator` is instantiated it instantiates a `JWT` object that in turn creates a `payload` set with an `expirationTime = Date().addingTimeInterval(expireDuration).timeIntervalSince1970`.

https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/58ab9330e94c0183ae51aaae972a7be9ca95555e/Sources/JWT/JWTRequestsAuthenticator.swift#L21
https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/58ab9330e94c0183ae51aaae972a7be9ca95555e/Sources/JWT/JWT.swift#L97-L99

The `expirationTime` is thus constant. When `JWTRequestsAuthenticator` renews the `cachedToken`, the new token is created with the original `expirationTime` which makes the jwt token invalid.

**Comment by jordibruin** [comment]
@AvdLee was this fixed?
