### ISSUE TITLE
Do we have latest_testflight_build_number (fastlane) API in SDK ?

### ISSUE THREAD

**Issue by iOSInk** [AvdLee/appstoreconnect-swift-sdk#147]
@AvdLee  Is there an API available that would return the latest build number when app version is passed ? For example an API that does what latest_testflight_build_number do in Fastlane

**Comment by AvdLee** [comment]
I'm not sure, honestly, I recommend looking into https://developer.apple.com/documentation/appstoreconnectapi for this and find the required information.

I'm closing this issue as it's not really an issue with the SDK, but more a support question.
