### ISSUE TITLE
User OpenAPI for generating code

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/appstoreconnect-swift-sdk#158]
Using [CreateAPI](https://kean.blog/post/create-api)

**Comment by kean** [comment]
App Store Connect spec is part of my test suite – it compiles. I haven't reviewed the generated code yet though.

**Comment by AvdLee** [comment]
> App Store Connect spec is part of my test suite – it compiles. I haven't reviewed the generated code yet though.

Ah, perfect! That's at least a good start. If I'm doing this, I want to set up a testing environment first that actually hits those endpoints so I'm sure things still work. Looking forward!
