### ISSUE TITLE
How to use ImageAsset.templateUrl for app icons?

### ISSUE THREAD

**Issue by aramusss** [AvdLee/appstoreconnect-swift-sdk#166]
Hi, this is not a bug but rather a question. When fetching a build's icon url, I can't seem to figure out how to get the image from the url. 

Endpoint:
```
let endpoint = APIEndpoint.apps(
  select: [.apps([.name]), .builds([.iconAssetToken])],
  include: [.builds],
  sortBy: [.bundleIdAscending],
  limits: [.builds(1)])
```

Response example:
https://is1-ssl.mzstatic.com/image/thumb/Purple/v4/b9/6b/ac/b96baceb-8545-8854-5795-c4b3e890def9/Icon-60@2x.png.png/{w}x{h}bb.{f}

Also, is there a best way to correlate App objects with Build objects inside `AppResponse.included` (since in this case I'm asking for all the apps and one build for app, but I get two separate arrays of `[App]` and `[AppRelationship.build(Build)]`)

Thank you for bringing this framework in Swift to life. I hope I can help improving it soon!

**Comment by MortenGregersen** [comment]
You need to replace the placeholders with the values like this: https://github.com/MortenGregersen/Bagbutik/blob/main/Sources/Bagbutik/Extensions/ImageAsset+URL.swift
