### ISSUE TITLE
Why Upgrade Swift Version 🤣 ?

### ISSUE THREAD

**Issue by mlch911** [AvdLee/appstoreconnect-swift-sdk#176]
I'm still stay in macOS 11. So I can only install Xcode 13.2.1 which use swift 5.5.
https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/91c6372116359b8fad216adf887c32acc8fbf5e5/Package.swift#L1

**Comment by AvdLee** [comment]
Fixed with the latest release, this was indeed not required to do! Hope it works for you again 🙂 
https://github.com/AvdLee/appstoreconnect-swift-sdk/releases/tag/2.0.1
