### ISSUE TITLE
No such Module "Get" In 2.0.0-beta1

### ISSUE THREAD

**Issue by bourvill** [AvdLee/appstoreconnect-swift-sdk#178]
Hello, after installing 2.0.0-beta1 I got an error during compile time

No such module Get in ApiProvider.swift

<img width="1456" alt="Capture d’écran 2022-07-20 à 11 52 21" src="https://user-images.githubusercontent.com/295272/179953595-17a8c919-1c7d-45da-82f1-029c71a61327.png">

**Comment by AvdLee** [comment]
This is fixed in the [latest release](https://github.com/AvdLee/appstoreconnect-swift-sdk/releases/tag/2.0.0)

**Comment by bourvill** [comment]
Hello not in 2.0.0-beta1
Maybe you can tag a beta2 from the master?

Actually I use the master for testing

**Comment by AvdLee** [comment]
@bourvill the SDK is no longer in beta, so you can use the non-beta 2.0.0 version: https://github.com/AvdLee/appstoreconnect-swift-sdk/releases/tag/2.0.0

**Comment by AvdLee** [comment]
I realize the previous version wasn't actually published. I just released 2.0.1 and made sure it's published: https://github.com/AvdLee/appstoreconnect-swift-sdk/releases/tag/2.0.1

Can you try it out?

**Comment by voxqhuy** [comment]
This is still an issue, what is the fix for this?
