### ISSUE TITLE
Disable certain SwiftLint warnings

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/appstoreconnect-swift-sdk#18]
We get several warnings for long class names, but we can't really do different for our models as the structure is just quite nice like it is now.

Warnings:

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          12 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Capabilities for AppStoreConnect-Swift-SDK_Example may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target ‘AppStoreConnect-Swift-SDK_Example’)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">ld: directory not found for option ‘-F/Applications/Xcode-10.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/Developer/Library/Frameworks’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">ld:</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/AppEncryptionDeclarationAppLinkageResponse.swift#L11">Sources/Models/AppEncryptionDeclarationAppLinkageResponse.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘AppEncryptionDeclarationAppLinkageResponse’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/AppEncryptionDeclarationBuildsLinkagesRequest.swift#L11">Sources/Models/AppEncryptionDeclarationBuildsLinkagesRequest.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘AppEncryptionDeclarationBuildsLinkagesRequest’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/BetaAppReviewSubmissionBuildLinkageResponse.swift#L11">Sources/Models/BetaAppReviewSubmissionBuildLinkageResponse.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘BetaAppReviewSubmissionBuildLinkageResponse’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/BetaBuildLocalizationBuildLinkageResponse.swift#L11">Sources/Models/BetaBuildLocalizationBuildLinkageResponse.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘BetaBuildLocalizationBuildLinkageResponse’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/BuildAppEncryptionDeclarationLinkageRequest.swift#L11">Sources/Models/BuildAppEncryptionDeclarationLinkageRequest.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘BuildAppEncryptionDeclarationLinkageRequest’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/BuildAppEncryptionDeclarationLinkageResponse.swift#L11">Sources/Models/BuildAppEncryptionDeclarationLinkageResponse.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘BuildAppEncryptionDeclarationLinkageResponse’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/BuildBetaAppReviewSubmissionLinkageResponse.swift#L11">Sources/Models/BuildBetaAppReviewSubmissionLinkageResponse.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘BuildBetaAppReviewSubmissionLinkageResponse’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/BuildBetaBuildLocalizationsLinkagesResponse.swift#L11">Sources/Models/BuildBetaBuildLocalizationsLinkagesResponse.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘BuildBetaBuildLocalizationsLinkagesResponse’</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/36f59bebf5549f02ced6283ae5d22020d2313bc4/Sources/Models/UserInvitationVisibleAppsLinkagesResponse.swift#L11">Sources/Models/UserInvitationVisibleAppsLinkagesResponse.swift#L11</a> - Type name should be between 3 and 40 characters long: ‘UserInvitationVisibleAppsLinkagesResponse’</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 4 tests, with 0 failures (0 unexpected) in 0.058 (0.123) seconds</td>
    </tr>
  </tbody>
</table>

**Comment by abhishekbanthia** [comment]
Hi @AvdLee, is the `.swiftlint-source.yml` file at Submodules/WeTransfer-iOS-CI needed to be modified for this?

**Comment by AvdLee** [comment]
@abhishekbanthia it was needed indeed, see the linked pull request.

Sorry if you were planning to pick this up. Feel free to work on another issue if you like to contribute!
