### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by Viktorianec** [AvdLee/appstoreconnect-swift-sdk#199]
Please add the application icon as an attribute, e.g. as a url if possible.

**Comment by AvdLee** [comment]
Hi @Viktorianec, can you be a bit more clear? This SDK is supporting all available paths and endpoints, so you should be able to get that Application icon if it's available in the API.

**Comment by Viktorianec** [comment]
Thank you for your reply, @AvdLee, you've done a huge amount of work. I tried to clarify if it is possible to extend the SDK to make it easier for developers to request certain things, like icons. Because so far it looks pretty non-trivial. I think we need to request a list of builds for each app, get the current one, and get an icon from it. That looks a bit complicated. In any case, thanks for the answer.

**Comment by AvdLee** [comment]
Right, I see what you mean! I don't think it's easy to add that with the automation we have in place right now using OpenAPI. Besides, I believe in most cases you would need the rest of the metadata that comes with the endpoint returning the app icon URL either way.

Thanks for replying!
