### ISSUE TITLE
Get Total Downloads for App

### ISSUE THREAD

**Issue by Peter-Schorn** [AvdLee/appstoreconnect-swift-sdk#209]
I would like to retrieve the total downloads for my app. I assume I will have to make multiple requests to a given endpoint with different time periods specified. However, I am a little overwhelmed by the complexity of this API and don't know where to begin. I'm hoping you can point me in the right direction.

**Comment by MortenGregersen** [comment]
I think the endpoint you are looking for is this: https://developer.apple.com/documentation/appstoreconnectapi/download_sales_and_trends_reports
