### ISSUE TITLE
Loading all of pricePoints

### ISSUE THREAD

**Issue by Viktor100500** [AvdLee/appstoreconnect-swift-sdk#232]
If I understand correctly, to load all the pricePoints, I have to scroll through the "pages" using the **links** - **next** field. But how can I call the ready URL using the already authorized APIEndpoint?

**Comment by nixta** [comment]
I think I have a similar question. I have 151 users and 90 apps. When listing users, the visibleApps are limited to 50. Some of the users have more visible apps than that. Is there a way to get the remaining page of visible apps for that user? Currently I'm having to make a separate paged call to list visible apps for user, but that seems much less efficient than using the visibleApps property on the user.

Thanks!

**Comment by AvdLee** [comment]
I'm pretty sure pagination is the answer to that, indeed!
