### ISSUE TITLE
Add xrOS to enum Platform

### ISSUE THREAD

**Issue by lhuanyu** [AvdLee/appstoreconnect-swift-sdk#237]
Several APIs, such as the response from the appCategories API, already return 'XR_OS', which can lead to decoding failures.

**Comment by MortenGregersen** [comment]
It returns `VISION_OS` now (https://github.com/MortenGregersen/Bagbutik/blob/b4f2d5b56d1b8938d5fb20c082f9e6d64e41462f/Sources/Bagbutik-Models/AppStore/Platform.swift#L19)

**Comment by polpielladev** [comment]
Closing this as this behaviour is already supported in the SDK 👍
