### ISSUE TITLE
Random crashes at JWTRequestsAuthenticator.adapt(_:)

### ISSUE THREAD

**Issue by nickasd** [AvdLee/appstoreconnect-swift-sdk#238]
Every now and then, after launching a debug session of my app in Xcode, when making the first call to `APIProvider.request(_:)` (`APIProvider.swift:194`),  the app crashes at `JWTRequestsAuthenticator.swift:39` with error
```
EXC_BAD_ACCESS (code=1, address=0xfffffffffffffff0)
```
The source code at that line only reads `return urlRequest`. The top of the stack trace is:
```
#0	0x0000000198b95370 in _swift_release_dealloc ()
#1	0x0000000198b96108 in bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) ()
#2	0x0000000100b61d44 in JWTRequestsAuthenticator.adapt(_:) at .../AppStoreConnectAPI/JWT/JWTRequestsAuthenticator.swift:39
```
Do you have any idea what the problem might be, and if this could potentially happen in a release build as well? I have cleaned and rebuilt the project many times in the meantime, but the crash still happens.

**Comment by nickasd** [comment]
It also just happened for the first time at `JWTRequestsAuthenticator.swift:31`, which reads `cachedToken = token`.
```
#0	0x0000000198b95370 in _swift_release_dealloc ()
#1	0x0000000198b96108 in bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) ()
#2	0x00000001006916b4 in JWTRequestsAuthenticator.createToken() at .../AppStoreConnectAPI/JWT/JWTRequestsAuthenticator.swift:31
```

**Comment by AvdLee** [comment]
This looks like a classic threading issue with a data race due to unsynchronized access. I don't have time soon to pick this up, but we should make it either an `actor` or set up some locking queues

**Comment by nickasd** [comment]
> This looks like a classic threading issue with a data race due to unsynchronized access. I don't have time soon to pick this up, but we should make it either an `actor` or set up some locking queues

Thanks for the tip. I have now changed it locally to `public final actor APIProvider`. I will see if that solves the issue and report back soon.
