### ISSUE TITLE
More recent version

### ISSUE THREAD

**Issue by amonshiz** [AvdLee/appstoreconnect-swift-sdk#241]
Hi!

It has been a while since the 2.3.0 release, almost year (Oct 31, 2022)! Can we expect to see a more recent release any time soon? Or is targeting `master` for the SPM dependency the most appropriate usage now instead of the version?

**Comment by AvdLee** [comment]
targeting `master` works best for now, but I'll see if I can boil a new version!

**Comment by AvdLee** [comment]
Done! https://github.com/AvdLee/appstoreconnect-swift-sdk/releases/tag/3.0.0

**Comment by AvdLee** [comment]
It's back now! Something was wrong with CI that deleted the tag after a release. Thanks for reporting in!
