### ISSUE TITLE
Vanished tag/release 3.0.0

### ISSUE THREAD

**Issue by andyj-at-aspin** [AvdLee/appstoreconnect-swift-sdk#243]
A notification subscription to this GitHub repository sent an email saying that there was a new release - 3.0.0 with API 2.3 support on 19th September 2023.

However, none of the links in that email work - all giving 404 from GitHub and this repository continues to state 2.3.0 is the latest tag/release.

Has this release been rolled back? If so, is it permitted to ask why?

**Comment by AvdLee** [comment]
It's back now! Something was wrong with CI that deleted the tag after a release. Thanks for reporting in!
