### ISSUE TITLE
Update CreateAPI to version 0.2.0

### ISSUE THREAD

**Issue by nickasd** [AvdLee/appstoreconnect-swift-sdk#248]
I've recently started looking at the options offered by CreateApi to customize the code generated for my own project, but the currently used version, 0.0.5, still uses the old option naming and doesn't support some newer options, so I've decided to try to update to 0.2.0. Before opening a PR, here are the changes that would happen to the existing code.

- The header comment lines `// swiftlint:disable all` are removed. If they are still wanted, the `fileHeaderComment` option could be extended to include it again. See https://github.com/CreateAPI/CreateAPI/pull/103
- operation ids are always added and `.get`, `.post` and `.patch` are replaced by `Request(method: "GET", url: path, body: body)` etc. E.g.
```
 public func get(fieldsSandboxTesters: [FieldsSandboxTesters]? = nil, limit: Int? = nil) -> Request<AppStoreConnect_Swift_SDK.SandboxTestersV2Response> {
    .get(path, query: makeGetQuery(fieldsSandboxTesters, limit))
 }
```
would become
```
 public func get(fieldsSandboxTesters: [FieldsSandboxTesters]? = nil, limit: Int? = nil) -> Request<AppStoreConnect_Swift_SDK.SandboxTestersV2Response> {
    Request(path: path, method: "GET", query: makeGetQuery(fieldsSandboxTesters, limit), id: "sandboxTestersV2-get_collection")
 }
```
See https://github.com/CreateAPI/CreateAPI/pull/102 and https://github.com/CreateAPI/CreateAPI/pull/83

Can I go on with a PR?

**Comment by AvdLee** [comment]
@nickasd thanks for checking in! I like the enum approach better, but I prefer to stay up to date with CreateAPI. In other words, please go ahead with the PR! If there's breaking changes, we can do a major version bump 👌

**Comment by nickasd** [comment]
I'll make the PR very soon. Just two more points I forgot to mention.
1) Is there a specific reason why `.create-api.yml` is a hidden file? At the beginning I was looking for a `.yml` file where the `CreateAPI` settings were stored, but since the file is hidden I couldn't find it in the Finder or in Xcode, so I had to find out what the path was by looking at `Plugins/CreateAPI/Plugin.swift`. I think making it visible by removing the leading period would make it easier for a new developer to find their way around the code.
2) Is it OK if I rename `app_store_connect_api_2.3_openapi.json` to `app_store_connect_api.json`? The `2.3` version number in the file name is currently wrong anyway. One would always have to think about updating the filename each time the API file is updated as well.

**Comment by AvdLee** [comment]
@nickasd both suggestions make totally sense to me!
