### ISSUE TITLE
Not able to initialize the models (User)

### ISSUE THREAD

**Issue by Blackjacx** [AvdLee/appstoreconnect-swift-sdk#25]
What I still miss is to initialize the models from my app e.g. to hand the user object to the network layer for updating. Could you add public initializers to the API? What do you think?

I need this to have a single point for creating a dictionary from the user object:

```swift
let attributes = User.Attributes(firstName: firstName, lastName: lastName, roles: roles, provisioningAllowed: provisioningAllowed, allAppsVisible: allAppsVisible, email: email)
let user = User(attributes: attributes, type: .userInvitations)
let parameters = user.serialized()
```

I have to do this in 2 places: 1) when creating it (invitation) and 2) when updating a user. For 1) I create a user from its details and after this create a dictionary from it and for 2) I clone the existing user object, change some attributes and serialize this. That way I have the serialization code in one place. Also for the clone function I need to be able to initialize my models.

I solved this that way:

```swift
init(id: String = "", attributes: User.Attributes?, type: ResourceType) {
      self.id = id
      self.type = type
      self.links = ResourceLinks(self: URL(string: "www.dumy.com")!)
      self.attributes = attributes
      self.relationships = nil
}
```

One hint: I would create another enum from `type` like my `ResourceType` in the code above. This way it gets reusable.

**Comment by AvdLee** [comment]
I think your suggestion makes a lot of sense! Do know that we're working on this more or less already, see [this](https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/24) PR.

This should already come close to what you need, but if not, feel free to open a PR with the requested changes.

**Comment by Blackjacx** [comment]
Yeah cool, think that solves my problem and even more ^^
