### ISSUE TITLE
Requesting appStoreVersionPhasedRelease returns nil data for version 1.0, which results in a decoding failure

### ISSUE THREAD

**Issue by acecilia** [AvdLee/appstoreconnect-swift-sdk#263]
👋 

Hi. I experienced that the following code:

```swift
let request = APIEndpoint.v1.appStoreVersions.id(version.id).appStoreVersionPhasedRelease.get(
    fieldsAppStoreVersionPhasedReleases: [.startDate]
)
let response = try await apiProvider.request(request)
```

Fails decoding the response and throws the following error:

```shell
Error: Failed to decode response:
{
  "data" : null,
  "links" : {
    "self" : "https://api.appstoreconnect.apple.com/v1/appStoreVersions/<redacted id>/appStoreVersionPhasedRelease?fields%5BappStoreVersionPhasedReleases%5D=startDate
  }
}
Error: valueNotFound(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [StringCodingKey(stringValue: "data", intValue: nil)], debugDescription: "Cannot get keyed decoding container -- found null value instead", underlyingError: nil)).
```

I believe is happening because the version-id I am requesting corresponds to a version `1.0`, meaning is the first time the app is being distributed, so doing phase release is impossible. Looks like appstoreconnect API communicates this by returning `"data" : null`, which is unexpected to the SDK that is trying to decode a non-null `data` property.

I am using version `2.3.0` of the SDK, but I believe the issue should also be present in latest version `3.X`, as the struct used for decoding which is [here](https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/2fb0578789a559a72782149d175ea5cf4184751c/Sources/OpenAPI/Generated/Entities/AppStoreVersionPhasedReleaseResponse.swift#L8) has not been changed in the past 2 years.

**Comment by J0s34h** [comment]
Having the same issue with - AppStoreVersionPhasedReleaseWithoutIncludesResponse, latest version

**Comment by J0s34h** [comment]
You might want to look at following merge request - https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/271

**Comment by acecilia** [comment]
Still an issue

**Comment by caka1011** [comment]
Hello. Can anyone share the code to fetch the last version submitted to the app store? Thanks

**Comment by polpielladev** [comment]
Hi @acecilia, sorry for the delay on this, I will make an action on my side to check this and get back to you tomorrow evening 👍

**Comment by polpielladev** [comment]
Hi! @acecilia, we're in the process of updating to the latest schema as part of https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/276. This PR includes fixes to the decoding of this endpoint. Could you confirm if the work on that branch fixes your problem?
