### ISSUE TITLE
AppStoreVersionState with removedFromSale never shows in app's AppStoreVersions

### ISSUE THREAD

**Issue by owenzhao** [AvdLee/appstoreconnect-swift-sdk#277]
When using v1 endpoint. 

1. I got apps.
2. For an app, got its appStoreVersions.
3. For an appStoreVersion, got its appStoreState.
4. List all apps with those appStoreVersions.

Here is the screenshot of app store connect website. The circled apps are "removed from sale".

<img width="1392" alt="截屏2024-06-18 19 32 57" src="https://github.com/AvdLee/appstoreconnect-swift-sdk/assets/2182896/7dfd9ed0-0f13-4dd7-954b-d610221353a9">

Here is the screenshot of my own app, there is no appStoreVersions with the state of "removed from sale". Any idea?

<img width="1699" alt="截屏2024-06-18 19 36 43" src="https://github.com/AvdLee/appstoreconnect-swift-sdk/assets/2182896/1bfbdab4-cf75-46c1-b2d2-e09e804c8c40">

**Comment by dluffymonkey** [comment]
请问一下，这里面App的展示的icon是从哪个属性里面获取到的，感谢   
Could you please tell me which attribute the App's display icon is retrieved from? Thank you.

**Comment by polpielladev** [comment]
Hi @owenzhao, I have been struggling with the same issue for my app Helm. From the tests I have done, I don't think the removed from sale state is actually returned by the API 😞 

I inspected the network traffic on App Store Connect, and it looks like they use a field called `legacyAppStoreState` that we don't have access to. We have done so already, but I would suggest filing a feedback request to Apple themselves.

```json
{
    "type" : "apps",
    "id" : "",
    "attributes" : {
      "removed" : false,
      "marketplace" : false,
      "appStoreLegacyStatus" : "DEVELOPER_REMOVED_FROM_SALE",
      "name" : "",
      "bundleId" : "",
      "sku" : "",
      "primaryLocale" : "en-US"
    },
}
```

**Comment by hanrw** [comment]
> 请问一下，这里面App的展示的icon是从哪个属性里面获取到的，感谢 Could you please tell me which attribute the App's display icon is retrieved from? Thank you.

e.g print("Build Attributes: \(String(describing: build.attributes?.iconAssetToken?.url))")
