### ISSUE TITLE
Replace withCheckedThrowingContinuation Calls With withUnsafeThrowingContinuation

### ISSUE THREAD

**Issue by AlexNsbmr** [AvdLee/appstoreconnect-swift-sdk#288]
First, thank you for maintaining this awesome library! 🙏

I wanted to report an issue we’re experiencing when using `withCheckedThrowingContinuation` on iOS 18, which is causing several crashes in our app. After investigating, it seems like replacing `withCheckedThrowingContinuation` with `withUnsafeThrowingContinuation` resolves the issue.

For reference, the team at RevenueCat has implemented a similar fix, and you can check out their approach here:
https://github.com/RevenueCat/purchases-ios/pull/4286

Would it be possible to make this update in the library as well?

Thank you for your attention to this issue!

**Comment by AvdLee** [comment]
@AlexNsbmr thanks for letting us know! Feel free to open a PR with the fix, happy to give it a review 🙏
