### ISSUE TITLE
Q:Extending expire duration in JWTRequestsAuthenticator

### ISSUE THREAD

**Issue by avinash-ramireddy** [AvdLee/appstoreconnect-swift-sdk#38]
Hi,

This is really helpful extension. I am currently working with pods.

I would like to set my expire duration instead of depending on pod expire duration.

It is set inside **JWTRequestsAuthenticator**

```
init(apiConfiguration: APIConfiguration) {
        self.apiConfiguration = apiConfiguration
        self.jwtCreator = JWT(keyIdentifier: apiConfiguration.privateKeyID, issuerIdentifier: apiConfiguration.issuerID, expireDuration: **60 * 20**)
    }
```

I would like to change 60 * 20 to something I want like 120 * 60.

/// The JWT Creator to use for creating the JWT token. Can be overriden for test use cases.
    var jwtCreator: JWTCreatable

This lines says we can override for test cases but I would like to still use pods and just expose expireDuration property only  instead of adding project manually into workspace.
 
Could you help me with this?

**Comment by AvdLee** [comment]
@avinash-ramireddy the expiration is set to the max allowed by the API. That is why it's not configurable, as the API requests would fail after that 20 minutes passed. 

Assuming this is answering your issue, I'm closing this issue for now.
