### ISSUE TITLE
Replace Alamofire with simplified URLSession implementation

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/appstoreconnect-swift-sdk#4]
As a simple API SDK, we should not rely on any dependencies ideally. It would be a great enhancement to replace Alamofire with a simplified layer on top of URL Session.

**Comment by rnystrom** [comment]
Would love to help out w/ this if you haven't started!

**Comment by schwmi** [comment]
Hi there, I am using the appstoreconnect-swift-sdk in my vapor app (thanks for providing this project open source 👍).  For the deployment on a linux server I needed a Alamofire free version. So I've implemented this here https://github.com/schwmi/appstoreconnect-swift-sdk/pull/1 
There is still some polishing to do - if you are interested I can open a PR to merge this back in.

**Comment by AvdLee** [comment]
@schwmi sounds good! I've quickly looked at your PR and with some small adjustments, it should be good to merge in and fix this issue.

Might not be exactly as @rnystrom proposed, but it's a good start at least!

**Comment by schwmi** [comment]
Sounds good! I’ll polish this PR next week when I‘m back from holiday and then open a new PR.
