### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by schwmi** [AvdLee/appstoreconnect-swift-sdk#40]
To allow users to deploy the sdk on Linux servers, CommonCrypto needs to be replaced (or complemented) by a Crypto-Lib which is available on Linux (e.g OpenSSL).
Linux compatibility opens up another set of use cases, e.g. giving your SlackBot the skill to invite a new Testflight user, get Build information, etc …
Our company bot marvin - which lives in a linux environment - already uses the sdk with these changes https://github.com/schwmi/appstoreconnect-swift-sdk/pull/3. Nevertheless, if we want to merge these changes back in, we should integrate it more nuanced s.t. iOS+macOS still uses CommonCrypto and OpenSSL is only used in a Linux environment.

What do you think @AvdLee?

**Comment by AvdLee** [comment]
It would be great to add Linux support, but not for any price. My goal with this SDK is to make it as easy as possible to use. Therefore, if we can come up with a plan to support iOS, macOS, and Linux in a way that they can all be supported easily, I would be happy to review that!

**Comment by schwmi** [comment]
Yep, I would integrate it in a way s.t. nothing changes for iOS/macOS user of the sdk.

**Comment by stefanhp** [comment]
Hi,
I came across a similar issue when adding SPM support in another project.
IBM has package for that: [IBM-Swift/BlueCryptor](https://github.com/IBM-Swift/BlueCryptor). It wraps CommonCrypto on Apple platforms and OpenSSL on Linux.
It would add a dependency: `.Package(url: "https://github.com/IBM-Swift/BlueCryptor.git", majorVersion: <majorVersion>, minor: <minor>)`.
Hope this helps.

**Comment by stefanhp** [comment]
I also found that there also is a pure Swift implementation: https://github.com/krzyzanowskim/CryptoSwift

**Comment by schwmi** [comment]
Had also a look at this lib - unfortunately doesn't support ES256 which is expected by apple as signatureAlogrithm for JWT

**Comment by aaronsky** [comment]
https://github.com/apple/swift-crypto could be a cool option, though it'd only work for iOS/tvOS 13+, watchOS 6.0+ and macOS 10.15+ on Apple platforms

**Comment by AvdLee** [comment]
@aaronsky good suggestion! I don't like dropping < iOS 13 anytime soon. If there's any other way of doing this I would prefer to do that.
