### ISSUE TITLE
Gimme them tags?

### ISSUE THREAD

**Issue by jeffctown** [AvdLee/appstoreconnect-swift-sdk#41]
IIUC - SPM requires semantic versioning and tagging to know how to pull the right version of a dependency.  

Is there any plan to add tags to this project?  I'd love to use it, but I don't think SPM will be able to pull down this project without tags.

From [swift.org](https://swift.org/package-manager/):

```Each dependency specifies a source URL and version requirements. The source URL is a URL accessible to the current user that resolves to a Git repository. The version requirements, which follow Semantic Versioning (SemVer) conventions, are used to determine which Git tag to check out and use to build the dependency. For the FisherYates dependency, the most recent version with a major version equal to 2 (for example, 2.0.4) will be used. Similarly, the PlayingCard dependency will use the most recent version with a major version equal to 3.```

When I add this project as a dependency in my `Package.swift` like you describe in the README, I receive this error:

<img width="815" alt="Screen Shot 2019-05-01 at 3 48 03 PM" src="https://user-images.githubusercontent.com/2142301/57038717-9709bc00-6c28-11e9-9192-08c396111ca4.png">

It looks like SPM thinks I am trying to use a local dependency since there is no `from` in my package dependency to tell SPM which tag to pull.

I'm using the latest Xcode (10.2.1 as of today), and here's the output of `swift --version`:

<img width="479" alt="Screen Shot 2019-05-01 at 3 50 30 PM" src="https://user-images.githubusercontent.com/2142301/57038825-e4862900-6c28-11e9-9e7c-bbb020541b5f.png">

I would paste my `Package.swift` here, but its literally one library, with only this one dependency.

**Comment by jeffctown** [comment]
When I download this repo, and add it as a local reference in my `Package.swift`, like ` .package(path: "/Users/jlett/appstoreconnect-swift-sdk/")` it works fine.

**Comment by beefon** [comment]
You can reference by commit. Also you can fork and add tags. 

But I’m big +1 to add tags to this repo. This should be no brainer.

**Comment by schwmi** [comment]
Hi, thanks for the issue. I've tagged the latest commit as 0.9.0 release (https://github.com/AvdLee/appstoreconnect-swift-sdk/releases/tag/0.9.0). @AvdLee are you ok with this start?

**Comment by AvdLee** [comment]
@schwmi totally makes sense to me! Thanks for fixing this :)

**Comment by AvdLee** [comment]
Also, updated the release of the releases page: https://github.com/AvdLee/appstoreconnect-swift-sdk/releases/tag/0.9.0
