### ISSUE TITLE
APIEndpoint.downloadSalesAndTrendsReports doesn't work

### ISSUE THREAD

**Issue by smallstep-zzz** [AvdLee/appstoreconnect-swift-sdk#42]
Hello

This "APIEndpoint.apps" was working well.
APIEndpoint.apps(
            select: [.apps([.name]), .builds([.version, .processingState, .uploadedDate])],
            include: [.builds],
            sortBy: [.bundleIdAscending],
            limits: [.apps(1)])

But "APIEndpoint.downloadSalesAndTrendsReports" is not working. 
let endpoint = APIEndpoint.downloadSalesAndTrendsReports(
            filter: [
                .reportType([.SALES]),
                .reportSubType([.SUMMARY]),
                .frequency([.WEEKLY]),
                .reportDate(["2019-01-01"]),
                .vendorNumber(["myVendorNumber"]),
            ])
        provider.request(endpoint) {
                switch $0 {
                case .success(let res):
                    print("success \(res)")
                case .failure(let error):
                    print("Something went wrong fetching the apps: \(error)")
                }
        }
Output window.
▿ FAILURE: requestFailure(400, nil)
  ▿ failure : Error
    ▿ requestFailure : 2 elements
      - .0 : 400
      - .1 : nil

So I test by cURL. cURL was working well. (I used JWTRequestsAuthenticator.createToken() for replace [token])
curl -v -H 'Authorization: Bearer [token]' --globoff "https://api.appstoreconnect.apple.com/v1/salesReports?filter[reportType]=SALES&filter[reportSubType]=SUMMARY&filter[frequency]=DAILY&filter[reportDate]=2019-01-01&filter[vendorNumber]=myVendorNumber" > output.gz

**Comment by AvdLee** [comment]
This might be fixed with the related PR. Can you try and see?

**Comment by hexagons** [comment]
I'm experiencing the same issue with both `.downloadSalesAndTrendsReports(...)` and `.downloadFinanceReports(...)`, with error status 400. Other endpoints work fine.

**Comment by Oleg-Ivanov** [comment]
Have the same issue too

**Comment by emilpedersen** [comment]
Same issue also

**Comment by AvdLee** [comment]
@hexagons @Oleg-Ivanov @emilpedersen feel free to open a PR for a fix! I'm happy to review it.

**Comment by hexagons** [comment]
@AvdLee I found the bug: https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/62

**Comment by hexagons** [comment]
Note when downloading weekly reports:
> For weekly reports, please specify the date of the Sunday ending the desired week.

**Comment by invoodoo** [comment]
Just tried to do salesAndTrends like that:
provider.request(.downloadSalesAndTrendsReports(filter: [.reportType([.SALES]), .frequency([.DAILY]), .reportDate(["2020-01-20"])]))

And got 400.

Was it fixed or this is something else? Apps request works well.

**Comment by AvdLee** [comment]
@invoodoo I'm in the process of releasing a new version of the SDK. It could be that you're still running old code if you're using Cocoapods, for example. Worth to verify!

**Comment by hexagons** [comment]
@invoodoo Make sure you got your `.vendorNumber(["########"])` in the request.

**Comment by invoodoo** [comment]
@AvdLee I use SPM and just master branch, no versions specified.

@hexagons what is the vendorNumber? Where to get it? Thanks.

**Comment by hexagons** [comment]
@invoodoo You can find your vendor number in the financial part of App Store Connect

**Comment by invoodoo** [comment]
@hexagons I did found, thanks, but unfortunately it didn't help still the same 400 error, waiting for @AvdLee update on SDK :)
