### ISSUE TITLE
Retrieving certificates list - no results

### ISSUE THREAD

**Issue by florinmatinca** [AvdLee/appstoreconnect-swift-sdk#63]
Hi guys,

I have an issue with retrieving the certificates list from my account, I was wondering if you experience the same issue. I have in my account three certificates: one development, one distribution, and one APNS.

This is the response I receive :

> CertificatesResponse(data: [], links: AppStoreConnect_Swift_SDK.PagedDocumentLinks(first: nil, next: nil, self: https://api.appstoreconnect.apple.com/v1/certificates), meta: Optional(AppStoreConnect_Swift_SDK.PagingInformation(paging: AppStoreConnect_Swift_SDK.PagingInformation.Paging(total: 0, limit: 20))))

The other endpoints are working just fine.

Thank you.

**Comment by BalestraPatrick** [comment]
I just tested it and I'm able to get back my 3 certificates with the following snippet:

```
provider.request(APIEndpoint.listDownloadCertificates()) {
    switch $0 {
        case .success(let response):
            print(response)
        case .failure(let error):
            print(error)
    }
}
```

The interesting thing is that the App Store Connect API only seem to return certificates which have a specific platform. So as you can see from the following picture, the certificates with platform set to "All" are not returned at all from the API. 

![Screen Shot 2020-01-07 at 10 07 23 AM](https://user-images.githubusercontent.com/3658887/71883089-f44df980-3135-11ea-934b-e4a4e0623f5c.png)
What's the platform of the certificates that you're expecting to be returned?

**Comment by florinmatinca** [comment]
Thanks a lot for your help.

Indeed, I had all the certificates for all platforms. However, there is one for push notifications associated with iOS, still, it's not visible in the response.

**Comment by BalestraPatrick** [comment]
Unfortunately, I think that's an issue with the App Store Connect API. The default request that we send is pretty standard with no parameters or filters, so if the API doesn't return the push notification certificate, there's not much we can do from our side. I suggest trying to reproduce the issue directly with the App Store Connect API (using Paw or something else to limit the variables in play) and file a radar with Apple about it.

Let me know if you find out something more and I'm happy to reopen this issue if you think it's a bug in our SDK and the App Store Connect API actually return it in the results.
