### ISSUE TITLE
Similar source files

### ISSUE THREAD

**Issue by onmyway133** [AvdLee/appstoreconnect-swift-sdk#67]
Hi, just curious that the these JWT components look pretty much the same, are they based on the same implementation some where?

https://github.com/AvdLee/appstoreconnect-swift-sdk/blob/master/Sources/JWT/ECPrivateKey.swift and https://github.com/ethanhuang13/CupertinoJWT/blob/master/Sources/ECPrivateKey.swift

**Comment by AvdLee** [comment]
Yes, they're mostly the same. The author of the other file is a contributor to this project as well.
