### ISSUE TITLE
how to support control Phased Release

### ISSUE THREAD

**Issue by lichanghong** [AvdLee/appstoreconnect-swift-sdk#75]
we all know that App Store connect have a function is called "Release a version update in phases"
can you sdk support Release a version update in phases? thank you

**Comment by AvdLee** [comment]
Thanks for your feedback, @lichanghong. I'm not entirely sure whether this is possible but feel free to open a PR and contribute to the project. I'll review your PRs accordingly.

**Comment by lichanghong** [comment]
thanks for your replay, I'm appreciate you will resolve this issue

**Comment by AvdLee** [comment]
> thanks for your replay, I'm appreciate you will resolve this issue

Sorry if I made you think I would solve this. I was telling you I'm happy to review any incoming PRs.
Unfortunately, I don't have the time to work on this myself. I hope you understand!
